name: Sync Changes to Local Server

on:
  push:
    branches:
      - master  # Se activa cuando hay un push a la rama 'master'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio remoto de GitHub
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Configurar la clave SSH para acceder al servidor
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.JESUS }}  # Clave SSH configurada en los secretos de GitHub

      # Paso 3: Sincronizar los cambios con el servidor local
      - name: Sync to Local Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.15.171.233 "cd /var/www/html/Semana2_P2/GPSpruebaFront && git pull origin master"
