name: UpdateRealTime

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 54.234.93.168 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Configure Git Remote
        run: |
          git remote add local ssh://ubuntu@54.234.93.168:/var/www/html/GPSUNINORTE || true
          git remote set-url local ssh://ubuntu@54.234.93.168:/var/www/html/GPSUNINORTE

      - name: Push Changes to Remote Repository
        run: |
          git push local master --force
