name: UpdateRealTime

on:
  push:
    branches:
      - master  # Este flujo se activará cuando haya cambios en la rama 'master'.

jobs:
  deploy:
    runs-on: ubuntu-latest  # La acción se ejecutará en una máquina virtual de Ubuntu.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Revisa el código del repositorio.

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.5  # Acción para SSH.
        with:
          host: ${{ secrets.AWS_HOST }}  # Tu IP de AWS.
          username: ${{ secrets.AWS_USER }}  # El usuario SSH de AWS (usualmente 'ubuntu').
          key: ${{ secrets.AWS_SSH_KEY }}  # La clave privada SSH de AWS.
          script: |
            cd /var/www/html/Semana2_P2/GPSpruebaFront/GPSUNINORTE  # Ruta de tu proyecto en la instancia de AWS.
            git pull origin SCRIP-OCT-JMLL  # Obtiene los cambios de la rama SCRIP-OCT-JMLL.
            # Puedes agregar otros comandos de despliegue aquí si es necesario.
